### PR TITLE
Added coordinates

### PR DESCRIPTION
**Pull request by bradennss**

### CODE REVIEW

**Comment by SuperOP535** [comment]
52 main_out.js:623 Uncaught ReferenceError: beginX is not defined
    at drawStats (main_out.js:623)
    at WebSocket.wsMessage (main_out.js:381)
10 main_out.js:623 Uncaught ReferenceError: beginX is not defined
    at drawStats (main_out.js:623)
    at WebSocket.wsMessage (main_out.js:381)

**Comment by bradennss** [comment]
Will fix this.

**Comment by SuperOP535** [comment]
ty

Den 30 nov 2017 23:10 skrev "Chewy!" <notifications@github.com>:

**Comment by ghost** [comment]
Thanks !

**Comment by Tetratrix** [comment]
@chewythepig can you please make a PR for the chat with html? I have already tried several times but without success...

**Comment by SuperOP535** [comment]
Yay I made some changes to my client and got this to work ( #115 )

**Pull request closed without merging**
