### PR TITLE
Added working coordinates to stats

### PR DESCRIPTION
**Pull request by SuperOP535**
Tested, it works 😃

### CODE REVIEW

**Comment by bradennss** [comment]
GG, sorry I didn’t have enough time to work on it yesterday.

**Comment by bradennss** [comment]
I’ll fix this today, these coordinates are inaccurate as they are for the minimap plane. I guess it doesn’t really matter if you’re just comparing coordinates with other players.

**Comment by SuperOP535** [comment]
Ok

**Comment by SuperOP535** [comment]
@chewythepig ehh u done??

**Comment by SuperOP535** [comment]
@chewythepig

**Comment by ChikoMalo** [comment]
@chewythepig  you can add color to the edge of the map

**Pull request closed without merging**
