### PR TITLE
Added multiple cell minimap drawing

### PR DESCRIPTION
**Pull request by Tombez**
In response to #130

### CODE REVIEW

**Comment by Tombez** [comment]
Seems Atom removed some whitespace without my say-so

**Comment by agarian-2** [comment]
If anything, push this to my fork, since it's the one with all the new features...

**Comment by Tombez** [comment]
Github says your fork is even with Luka967/Cigar though...

**Comment by agarian-2** [comment]
https://github.com/agarian-2/agarian-2.github.io

**Comment by Tombez** [comment]
Ah, I checked your other account.

**Comment by SuperOP535** [comment]
@Tombez https://discord.gg/66X2ESb :)

**Review by SomeoneCares11 — APPROVED** [review]

**Comment by SomeoneCares11** [comment]
cells too small, i made them bigger by 
`var r = (cell.s * xScaler) + 1;`
We may add an option to gameserver to make cells bigger in minimap ?

**Comment by Tombez** [comment]
I kinda expected someone might say they look too small, that's fine.

**Comment by SomeoneCares11** [comment]
Thanks btw. you did nice job on this, hope you PR mobile touches someday

**Comment by agarian-2** [comment]
The sizes are fine in my opinion...

**Review by SuperOP535 — APPROVED** [review]

**Comment by agarian-2** [comment]
k

**Comment by bradennss** [comment]
You guys need some assistance?

**Comment by Tombez** [comment]
I don't think so, just waiting for Luka to merge the PR.

**Comment by agarian-2** [comment]
I don't think Luka will, I don't think she (or he, I may be assuming gender O_o) wants her client changed in the first place.

**Comment by Tombez** [comment]
Well then, they should just say that. I was under the impression there was an active community around Luka's Cigar, but if I'm mistaken, it would help if Luka said something about it. Either via a comment or in the readme.

https://github.com/Luka967/Cigar/blob/master/CONTRIBUTING.md is very misleading if Luka is not accepting pull requests.

**Comment by SomeoneCares11** [comment]
Luka currently busy with a new Multiogar rewrite, he will check soon.

**Comment by bradennss** [comment]
He’s left this in the dust. I am friends with him and in very close contact with him. He has directly stated that he plans to write a new Cigar-like client from scratch with cleaner code and better commenting, similar to his take on MO/MO-E with OgarII.

**Comment by agarian-2** [comment]
I don't see why he'd just leave this one behind though.

**Comment by bradennss** [comment]
Because the project is actual shit.

**Comment by bradennss** [comment]
We all need a new client, let’s face it.

**Comment by agarian-2** [comment]
Wrong, I use this all the time (since agar.io does not work with MultiOgar anymore).

**Comment by Tombez** [comment]
It's true the project could use a complete rewrite, but it works for a lot of people.

**Comment by bradennss** [comment]
True, it’s a dinosaur in the sense that it’s had a lot of time to improve. It’s also good for people that want to spin up something quick just to fuck off on MO-E. *However*, it is terrible for production use (for example, if you want to make a game with it), as it requires a web server supporting PHP and has no built in bundling setup for caching purposes (like WebPack). My game, https://popsplit.us, was built with Lukas fork of Cigar (this repo), but it is nothing alike on the backend. Most changes go through bundling in the development server before they even make it to production. Bundling renames these files to random MD5 hashes depending on their content, destroying normal browser caching allowing changes to take affect immediately. But, sadly, none of this comes out of the box. Setting up your own environment to get this to work efficient for a decently sized game requires some work.

**Comment by Tombez** [comment]
Turns out I need to close this PR and create a new one to change the source branch :/

**Pull request closed without merging**
