### PR TITLE
Border lines with option to disable them!

### PR DESCRIPTION
**Pull request by SuperOP535**

### CODE REVIEW

**Comment by agarian-2** [comment]
I'm not sure that Luka's gonna accept this. I say close it, I've pushed it to my for already.

**Comment by Tombez** [comment]
Am I missing something, or did you not declare `setBorders` anywhere?

**Comment by SuperOP535** [comment]
Whoops sorry I forgot to copy all of the code from my copy, fixing in a sec

**Comment by agarian-2** [comment]
@SuperOP535 Add the following above `wHandle.spectate` (line 1338):
```js
wHandle.setBorders = function(a) {
    settings.showBorders = a;
};
```

**Comment by SuperOP535** [comment]
@agarian-2 Ik

**Comment by SuperOP535** [comment]
@agarian-2 I've made it as No borders and not Show borders so I used my own version

**Comment by SuperOP535** [comment]
This has been implemented at Cigar2 https://github.com/Cigar2/Cigar2

**Comment by agarian-2** [comment]
k

**Pull request closed without merging**
